---
abstract: 'Hypertext Application Language resource'
author:
  - 'Lars DÉªá´á´á´á´á´¡ C<< <daxim@cpan.org> >>'
build_requires:
  Data::Visitor::Callback: 0
  File::Slurp: 0
  JSON: 0
  Log::Any::Adapter: 0
  Log::Any::Adapter::FileHandle: 0
  Test::Fatal: 0
  Test::More: 0
  strictures: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 0
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-HAL
no_index:
  file:
    - lib/Data/HAL/URI/NamespaceMap.pm
provides:
  Data::HAL:
    file: lib/Data/HAL.pm
    version: 1.000
  Data::HAL::Link:
    file: lib/Data/HAL/Link.pm
    version: 1.000
  Data::HAL::URI:
    file: lib/Data/HAL/URI.pm
    version: 1.000
  Data::HAL::URI::NamespaceMap:
    file: lib/Data/HAL/URI/NamespaceMap.pm
    version: 1.000
requires:
  Clone: 0
  Data::Visitor::Callback: 0
  HTTP::Headers::Util: 0
  JSON: 0
  Log::Any: 0
  MIME::Type: 0
  Moo: 0
  Safe::Isa: 0
  Scalar::Util: 0
  Types::Standard: 0
  URI: 0
  URI::IRI: 0
  URI::NamespaceMap: 0
  URI::Template: 0
  XML::RegExp: 0
  boolean: 0
  failures: 0
  perl: 5.008
  strictures: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000
